title: Jr Dev
subtitle: Keeping software simple
author:
avatar_url: https://raw.githubusercontent.com/KamRon-67/jrdev.io/master/assets/img/avatar.png  # Should be 160x160px.
description: > # this means to ignore newlines until "twitter_username:"
  Jr Dev is a blog about technology, software, management, and things that are helpful for new devs.
repository: https://github.com/KamRon-67/jrdev.io

description: > # this means to ignore newlines until "twitter_username:"
  This is a blog about
  Technology, Software, Management, and Open Source stuff.

# Google Analytics
google_analytics: UA-149577567-1

# contact
contact:
  email:  # Comment out this line if you don't want to expose your email.
  url: https://github.com/KamRon-67/jrdev.io/issues/new # Uncomment this to provide a contact form url instead of an email

# social links
twitter_username: PatriceThePlant
github_username:  KamRon-67
rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekylld

#
# Subscribe Feed
#
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
# feed:
#   path: /atom.xml

# If you use a feed publisher such as Feedburner, uncomment the next line
subscribe_rss: http://feeds.feedburner.com/JrDev

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
comments:
  enabled: true
  show_count: false
#  receiver:
  disqus_shortname: jr-dev-1

emptyArray: [] # Leave this here.

# haackbar date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
haackbar:
  date_format: "%b %-d, %Y"

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 2 # number of posts per page
page_group_size: 2 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"

# Front matter defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache
